# Form implementation generated from reading ui file 'DialogWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(543, 435)
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 501, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_mac = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_mac.setObjectName("lineEdit_mac")
        self.gridLayout.addWidget(self.lineEdit_mac, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_model = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.gridLayout.addWidget(self.lineEdit_model, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_drum = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_drum.setObjectName("lineEdit_drum")
        self.gridLayout.addWidget(self.lineEdit_drum, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_cartridge = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_cartridge.setObjectName("lineEdit_cartridge")
        self.gridLayout.addWidget(self.lineEdit_cartridge, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.gridLayout.addWidget(self.lineEdit_ip, 3, 1, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 8, 0, 1, 2)
        self.lineEdit_place = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_place.setObjectName("lineEdit_place")
        self.gridLayout.addWidget(self.lineEdit_place, 5, 1, 1, 1)
        self.lineEdit_place_building = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_place_building.setObjectName("lineEdit_place_building")
        self.gridLayout.addWidget(self.lineEdit_place_building, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Место :"))
        self.label.setText(_translate("Dialog", "Модель :"))
        self.label_2.setText(_translate("Dialog", "Картридж :"))
        self.label_4.setText(_translate("Dialog", "Ip address :"))
        self.label_3.setText(_translate("Dialog", "Барабан :"))
        self.label_5.setText(_translate("Dialog", "mac :"))
        self.pushButton_send.setText(_translate("Dialog", "Записать"))
        self.lineEdit_place_building.setPlaceholderText(_translate("Dialog", "B1F3"))
        self.label_7.setText(_translate("Dialog", "Здание"))
